# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ron's Musings
email: roncham@gmail.com
description: >
  Life, Outdoors & Code
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://roncham.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Ron'
bio: >
  I love the outdoors and if there was wifi on top of the mountain, that’s where you would find me.
author_image: "/assets/images/ron_bw.png"
twitter_username: cstmizd
github_username:  roncham

# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems:
  - jekyll-paginate
